### ISSUE TITLE
New extension & Update

### ISSUE THREAD

**Issue by InzamamulQureshi** [Suwayomi/tachiyomi-extension#1]
### Describe your suggested feature

Can you add extension for manga demon, and also please update manhwa plus extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by Syer10** [comment]
Wtf, this is not a repo for those kind of sources. This is the repo for the Suwayomi extension for Tachiyomi/Mihon. Go ask in the correct places for those things.
