### ISSUE TITLE
Extension 

### ISSUE THREAD

**Issue by Igrisredblood** [Suwayomi/tachiyomi-extension#10]
### Describe your suggested feature

For cosmicsan the domain changed to cosmic1.co
And for komikindo it changed to komiksin.id
Please update it

### Other details

That's it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

**Comment by Syer10** [comment]
The Suwayomi extension is unrelated to that domain, please report your issue to the correct repository.
