### ISSUE TITLE
Koharu extension loading thumbnail but not loading the manga

### ISSUE THREAD

**Issue by Farzout** [Suwayomi/tachiyomi-extension#7]
### Steps to reproduce

as said

### Expected behavior

as said

### Actual behavior

as said

### App version

0.16.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [X] I will fill out all of the requested information in this form.

**Comment by Syer10** [comment]
That extension is not managed by Suwayomi, report the issue to your extension repo.
