### ISSUE TITLE
Cannot install this extension in Mihon

### ISSUE THREAD

**Issue by WROIATE** [Suwayomi/tachiyomi-extension#9]
### Steps to reproduce

1. add `https://raw.githubusercontent.com/suwayomi/tachiyomi-extension/repo/index.min.json` into Mihon
2. click install

### Expected behavior

Install this extension

### Actual behavior

Get 404 code

### App version

0.16.5

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [X] I will fill out all of the requested information in this form.

**Comment by WROIATE** [comment]
Maybe forgot to bump the version info?
![image](https://github.com/user-attachments/assets/ef5430cb-bb2c-4217-a66a-30c558cb22dd)
![image](https://github.com/user-attachments/assets/299d42d3-8276-4a70-a986-d5701f26a1de)

**Comment by Syer10** [comment]
The heck, how did the repo.json not get updated
